# Generated by Django 4.2.1 on 2023-06-07 15:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=16)),
                ('etat', models.BooleanField(default=False)),
                ('maintenanceDate', models.DateField(default=django.utils.timezone.now)),
                ('crea', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('description', models.TextField(default='/')),
                ('date_mise_a_jour_infra', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='infrastructures', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_mise_a_jour_infra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(default='', max_length=16)),
                ('prenom', models.CharField(default='', max_length=16)),
                ('email', models.EmailField(blank=True, editable=False, max_length=254)),
                ('role', models.CharField(choices=[('Resp.', 'Resp.Paris'), ('Resp.', 'Resp.Poitiers'), ('Resp.', 'Resp.Marseille'), ('Resp.', 'Resp.Lyon'), ('Employé', 'Employé')], default='Employé', max_length=100)),
                ('crea', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('Infrastructure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='computerApp.infrastructure')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=16)),
                ('maintenanceDate', models.DateField(default=datetime.datetime(2023, 6, 14, 17, 26, 44, 541896))),
                ('mach', models.CharField(choices=[('PC', 'PC - Run windows'), ('Mac', 'Mac - Run MacOS'), ('Serveur', 'Serveur - Simple Server to deploy virtual machines'), ('Switch', 'Switch - To maintains and connect servers')], default='PC', max_length=32)),
                ('etat', models.BooleanField(default=False)),
                ('creation', models.DateField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(default='/')),
                ('appartient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.personnel')),
                ('infra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.infrastructure')),
                ('utilisateur_mise_a_jour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
