# Generated by Django 4.0.4 on 2022-05-01 19:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('computerapp', '0004_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 5, 1, 19, 11, 27, 779774, tzinfo=utc)),
        ),
    ]
