# Generated by Django 4.2.1 on 2023-06-07 15:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerApp', '0004_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='adresse_ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=15),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='utilisateur_mise_a_jour_infra',
            field=models.ForeignKey(blank=True, default='admin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 14, 17, 37, 54, 909897)),
        ),
    ]
