# Generated by Django 4.2.1 on 2023-05-20 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0009_machine_etat_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='appartient_nom',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='machine',
            name='appartient_prenom',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
