# Generated by Django 4.2.1 on 2023-05-20 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0011_remove_machine_appartient_nom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='creation',
            field=models.DateField(default=datetime.datetime(2023, 5, 20, 15, 31, 45, 23402)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 27, 15, 31, 45, 23402)),
        ),
    ]
