# Generated by Django 4.2.1 on 2023-05-20 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0013_alter_machine_creation_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 27, 15, 40, 53, 280924)),
        ),
    ]
