# Generated by Django 4.2.1 on 2023-05-20 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0017_alter_machine_maintenancedate_alter_personnel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 27, 15, 48, 16, 989507)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='email',
            field=models.EmailField(default='<django.db.models.fields.CharField>.<django.db.models.fields.CharField>@RTdev.com', max_length=254),
        ),
    ]
