# Generated by Django 4.2.1 on 2023-05-21 09:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0023_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='appartient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 14, 39, 218682)),
        ),
    ]
