# Generated by Django 4.2.1 on 2023-05-21 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0025_infrastructure_personnel_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 20, 41, 972086)),
        ),
    ]
