# Generated by Django 4.2.1 on 2023-05-21 09:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0027_alter_machine_maintenancedate_alter_personnel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 28, 46, 385373)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='infrastructure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.infrastructure'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('Resp.', 'Resp.'), ('Employé', 'Employé')], default='Employé', max_length=100),
        ),
    ]
