# Generated by Django 4.2.1 on 2023-05-21 09:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0028_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 30, 50, 577830)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.infrastructure'),
        ),
    ]
