# Generated by Django 4.2.1 on 2023-05-21 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0029_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 11, 34, 31, 840266)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 34, 31, 841266)),
        ),
    ]
