# Generated by Django 4.2.1 on 2023-05-21 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0030_personnel_crea_alter_machine_maintenancedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 11, 37, 55, 703534), editable=False),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 37, 55, 703534)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 28, 11, 37, 55, 729540)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 5, 21, 11, 37, 55, 728539), editable=False),
        ),
    ]
