# Generated by Django 4.2.1 on 2023-05-22 15:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0036_alter_infrastructure_crea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='infra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='computerApp.infrastructure'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 17, 8, 17, 586898), editable=False),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 17, 8, 17, 586898)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 17, 8, 17, 613904)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 5, 22, 17, 8, 17, 612904), editable=False),
        ),
    ]
