# Generated by Django 4.2.1 on 2023-06-06 14:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerApp', '0039_alter_infrastructure_crea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 54, 4, 141198), editable=False),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 16, 54, 4, 141198)),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='utilisateur_mise_a_jour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 16, 54, 4, 143198)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 54, 4, 142198), editable=False),
        ),
    ]
