# Generated by Django 4.2.1 on 2023-06-06 14:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerApp', '0040_alter_infrastructure_crea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='date_mise_a_jour',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='utilisateur_mise_a_jour',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='date_mise_a_jour_infra',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='utilisateur_mise_a_jour_infra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 56, 21, 866445), editable=False),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 16, 56, 21, 866445)),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 16, 56, 21, 867445)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='crea',
            field=models.DateField(default=datetime.datetime(2023, 6, 6, 16, 56, 21, 867445), editable=False),
        ),
    ]
