# Generated by Django 4.2.1 on 2023-06-06 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0045_alter_infrastructure_maintenancedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='infrastructure',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='personnel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure', to='computerApp.personnel'),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='maintenanceDate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 17, 37, 37, 479440)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='crea',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
    ]
