# Generated by Django 4.2.1 on 2023-06-06 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0046_remove_personnel_infrastructure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='personnel',
        ),
        migrations.AddField(
            model_name='personnel',
            name='infrastructure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='computerApp.infrastructure'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 17, 40, 5, 325739)),
        ),
    ]
