# Generated by Django 4.2.1 on 2023-06-06 15:43

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerApp', '0047_remove_infrastructure_personnel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='users',
            field=models.ManyToManyField(related_name='infrastructures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 17, 43, 17, 872524)),
        ),
    ]
