# Generated by Django 4.2.1 on 2023-06-06 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0049_remove_infrastructure_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 17, 53, 45, 958037)),
        ),
    ]
