# Generated by Django 4.2.1 on 2023-06-06 16:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0051_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='responsable',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsabilite', to='computerApp.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 18, 4, 6, 463729)),
        ),
    ]
