# Generated by Django 4.2.1 on 2023-06-06 16:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerApp', '0052_remove_infrastructure_utilisateur_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='responsable',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 18, 6, 32, 83711)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='infrastructure',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='computerApp.infrastructure'),
        ),
    ]
