# Generated by Django 4.2.1 on 2023-06-06 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0054_remove_infrastructure_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 18, 12, 42, 586651)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='infrastructure',
            field=models.OneToOneField(blank=True, limit_choices_to=('Resp.', 'Resp.'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='computerApp.infrastructure'),
        ),
    ]
