# Generated by Django 4.2.1 on 2023-06-06 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0058_alter_machine_maintenancedate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='users',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='responsable_lyon',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'Resp.Lyon'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_lyon', to='computerApp.personnel'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='responsable_marseille',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'Resp.Marseille'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_marseille', to='computerApp.personnel'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='responsable_paris',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'Resp.Paris'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_paris', to='computerApp.personnel'),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='responsable_poitiers',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'Resp.Poitiers'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infrastructure_poitiers', to='computerApp.personnel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 18, 20, 29, 847758)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='infrastructure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnel', to='computerApp.infrastructure'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('Resp.Paris', 'Resp.Paris'), ('Resp.Poitiers', 'Resp.Poitiers'), ('Resp.Marseille', 'Resp.Marseille'), ('Resp.Lyon', 'Resp.Lyon'), ('Employé', 'Employé')], default='Employé', max_length=100),
        ),
    ]
