# Generated by Django 4.2.1 on 2023-06-06 16:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('computerApp', '0059_remove_infrastructure_users_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructure',
            name='responsable_lyon',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='responsable_marseille',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='responsable_paris',
        ),
        migrations.RemoveField(
            model_name='infrastructure',
            name='responsable_poitiers',
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='users',
            field=models.ManyToManyField(related_name='infrastructures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2023, 6, 13, 18, 25, 10, 24351)),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.CharField(choices=[('Resp.', 'Resp.Paris'), ('Resp.', 'Resp.Poitiers'), ('Resp.', 'Resp.Marseille'), ('Resp.', 'Resp.Lyon'), ('Employé', 'Employé')], default='Employé', max_length=100),
        ),
    ]
